
import java.io.IOException;
import java.io.RandomAccessFile;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Minh Thanh
 */
public class Form1 extends javax.swing.JFrame {

    EmployeeList list;
    DefaultTableModel t;

    public Form1() {
        initComponents();
        t = (DefaultTableModel) tbl1.getModel();
        list = new EmployeeList();
        rdtbnMale.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtSalary = new javax.swing.JTextField();
        txtBonus = new javax.swing.JTextField();
        btnLoadDisplay = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnSort = new javax.swing.JButton();
        btnSearchExact = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl1 = new javax.swing.JTable();
        btnClear = new javax.swing.JButton();
        btnInsertAt = new javax.swing.JButton();
        btnRemoveSelected = new javax.swing.JButton();
        txtInsertAt = new javax.swing.JTextField();
        txtNameSearch = new javax.swing.JTextField();
        txtDeleteRow = new javax.swing.JTextField();
        btnDeleteByName = new javax.swing.JButton();
        rdtbnMale = new javax.swing.JRadioButton();
        rdbtnFemale = new javax.swing.JRadioButton();
        btnSearchRelative = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Employee Management");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Code: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Name:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Sex:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Salary:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Bonus:");

        btnLoadDisplay.setText("Load & Display from file");
        btnLoadDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadDisplayActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnSort.setText("Sort");
        btnSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortActionPerformed(evt);
            }
        });

        btnSearchExact.setText("Search Exact Name:");
        btnSearchExact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchExactActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete row:");

        tbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Name", "Sex", "Salary", "Bonus", "Income"
            }
        ));
        jScrollPane1.setViewportView(tbl1);

        btnClear.setText("Clear All");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnInsertAt.setText("Insert At:");
        btnInsertAt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertAtActionPerformed(evt);
            }
        });

        btnRemoveSelected.setText("Remove selected row");
        btnRemoveSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveSelectedActionPerformed(evt);
            }
        });

        btnDeleteByName.setText("Delete by name:");
        btnDeleteByName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteByNameActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdtbnMale);
        rdtbnMale.setText("Male");
        rdtbnMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdtbnMaleActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbtnFemale);
        rdbtnFemale.setText("Female");

        btnSearchRelative.setText("Search Relative");
        btnSearchRelative.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchRelativeActionPerformed(evt);
            }
        });

        jLabel7.setText("Name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLoadDisplay)
                            .addComponent(jLabel1)
                            .addComponent(btnAdd)
                            .addComponent(btnSort)
                            .addComponent(btnClear)
                            .addComponent(btnRemoveSelected)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnDelete)
                                    .addComponent(btnInsertAt))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtInsertAt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDeleteRow, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdbtnFemale)
                            .addComponent(rdtbnMale))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSearchRelative)
                    .addComponent(btnSearchExact)
                    .addComponent(btnDeleteByName))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(btnAdd)
                                .addGap(18, 18, 18)
                                .addComponent(btnSort)
                                .addGap(18, 18, 18)
                                .addComponent(btnClear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRemoveSelected)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnInsertAt)
                                    .addComponent(txtInsertAt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDeleteRow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLoadDisplay))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(rdtbnMale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdbtnFemale))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel4)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtBonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(btnSearchRelative)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchExact)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeleteByName)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortActionPerformed
        list.sortByName();
        updateTable(list);
    }//GEN-LAST:event_btnSortActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String xCode = txtCode.getText().trim();
        String xName = txtName.getText().trim();
        boolean sSex = rdtbnMale.isSelected();
        String xSex = "";
        String sSalary = txtSalary.getText().trim();

        String sBonus = txtBonus.getText().trim();

        boolean isOk = true;
        if (xCode.equals("")) {
            isOk = false;
        }
        if (xName.equals("")) {
            isOk = false;
        }
        if (sSalary.equals("")) {
            isOk = false;
        }
        if (sBonus.equals("")) {
            isOk = false;
        }

        if (!isOk) {
            JOptionPane.showMessageDialog(null, "The data cannot be empty");
            return;
        }
        if (sSex) {
            xSex = "Male";
        } else {
            xSex = "Female";
        }
        double xSalary = Double.parseDouble(sSalary);
        double xBonus = Double.parseDouble(sBonus);
        double xIncome = xSalary + xBonus;
        list.add(new Employee(xCode, xName, xSex, xSalary, xBonus, xIncome));
        Object[] a = {xCode, xName, xSex, xSalary, xBonus, xIncome};
        t.addRow(a);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearTable();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnRemoveSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveSelectedActionPerformed
        int k = tbl1.getSelectedRow();
        t.removeRow(k);
    }//GEN-LAST:event_btnRemoveSelectedActionPerformed

    private void btnInsertAtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertAtActionPerformed
        String xCode = txtCode.getText().trim();
        String xName = txtName.getText().trim();
        boolean sSex = rdtbnMale.isSelected();
        String xSex = "";
        String sSalary = txtSalary.getText().trim();

        String sBonus = txtBonus.getText().trim();

        boolean isOk = true;
        if (xCode.equals("")) {
            isOk = false;
        }
        if (xName.equals("")) {
            isOk = false;
        }
        if (sSalary.equals("")) {
            isOk = false;
        }

        if (sBonus.equals("")) {
            isOk = false;
        }

        if (!isOk) {
            JOptionPane.showMessageDialog(null, "The data cannot be empty");
            return;
        }
        if (sSex) {
            xSex = "Male";
        } else {
            xSex = "Female";
        }

        double xSalary = Double.parseDouble(sSalary);
        double xBonus = Double.parseDouble(sBonus);
        double xIncome = xSalary + xBonus;
        Object[] a = {xCode, xName, xSex, xSalary, xBonus, xIncome};
        String x = txtInsertAt.getText().trim();
        int k, n;
        n = tbl1.getRowCount();
        k = Integer.parseInt(x);
        if (k < 0 || k > n) {
            return;
        }
        t.insertRow(k, a);
    }//GEN-LAST:event_btnInsertAtActionPerformed

    private void rdtbnMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdtbnMaleActionPerformed

    }//GEN-LAST:event_rdtbnMaleActionPerformed

    void fileToTable(String fname) throws IOException {
        RandomAccessFile f = new RandomAccessFile(fname, "r");
        String s;
        String[] a;
        String xName, xCode, xSex;
        double xSalary, xBonus, xIncome;
        while (true) {
            s = f.readLine();
            if (s == null || s.length() < 6) {
                break;
            }
            a = s.split("[|]");
            xCode = a[0].trim();
            xName = a[1].trim();
            xSex = a[2].trim();
            xSalary = Double.parseDouble(a[3].trim());
            xBonus = Double.parseDouble(a[4].trim());
            xIncome = Double.parseDouble(a[5].trim());
            Object[] b = {xCode, xName, xSex, xSalary, xBonus, xIncome};
            t.addRow(b);
        }
        f.close();
    }
    private void btnLoadDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadDisplayActionPerformed
        String filename = "Employee.txt";
        try{
            //EmployeeList em = new EmployeeList();
            fileToTable(filename);
            //em.inputFromFile(filename);
        }catch (Exception e){
            
        }
        
        
    }//GEN-LAST:event_btnLoadDisplayActionPerformed

    private void btnDeleteByNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteByNameActionPerformed
        String xName, sName;
        xName = txtNameSearch.getText().trim();
        int i, n, k;
        i = list.searchByName(xName);
        list.delete(i);

        n = tbl1.getRowCount();
        k = -1;
        for (i = 0; i < n; i++) {
            sName = (String) tbl1.getValueAt(i, 1);
            sName = sName.trim();
            if (sName.equals(xName)) {
                k = i;
            }
        }
        if (k > -0) {
            t.removeRow(k);
        }

    }//GEN-LAST:event_btnDeleteByNameActionPerformed

    private void btnSearchExactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchExactActionPerformed
        String xName = txtNameSearch.getText().trim();
        EmployeeList h = new EmployeeList();
        list.searchByName(h, xName);
        updateTable(h);
    }//GEN-LAST:event_btnSearchExactActionPerformed

    private void btnSearchRelativeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchRelativeActionPerformed
        String xName = txtNameSearch.getText().trim();
        EmployeeList h = new EmployeeList();
        list.searchByNameRel(h, xName);
        updateTable(h);
    }//GEN-LAST:event_btnSearchRelativeActionPerformed

    
    void clearTable() {
        int n, i;
        n = tbl1.getRowCount();
        for (i = 0; i < n; i++) {
            t.removeRow(0);
        }

    }
    
    void updateTable(EmployeeList v) {        
        int n, i;
        Employee x;
        n = v.size();
        for (i = 0; i < n; i++) {
            x = v.get(i);
            t.insertRow(tbl1.getRowCount(), new Object[6]);
            tbl1.setValueAt(x.code, i, 0);
            tbl1.setValueAt(x.name, i, 1);
            tbl1.setValueAt(x.sex, i, 2);
            tbl1.setValueAt(x.salary, i, 3);
            tbl1.setValueAt(x.bonus, i, 4);
            tbl1.setValueAt(x.income, i, 5);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteByName;
    private javax.swing.JButton btnInsertAt;
    private javax.swing.JButton btnLoadDisplay;
    private javax.swing.JButton btnRemoveSelected;
    private javax.swing.JButton btnSearchExact;
    private javax.swing.JButton btnSearchRelative;
    private javax.swing.JButton btnSort;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdbtnFemale;
    private javax.swing.JRadioButton rdtbnMale;
    private javax.swing.JTable tbl1;
    private javax.swing.JTextField txtBonus;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtDeleteRow;
    private javax.swing.JTextField txtInsertAt;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNameSearch;
    private javax.swing.JTextField txtSalary;
    // End of variables declaration//GEN-END:variables
}
