
import context.DBContext;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Minh Thanh
 */
public class Form1 extends javax.swing.JFrame {

    private static final Scanner sc = new Scanner(System.in);

    Connection con = null; // mo ket noi toi sql
    Statement statement; // nem query tu netbean sang sql server
    ResultSet rs; // nhan kq tra ve
    DBContext t = new DBContext(); ///////////
    DefaultTableModel dt;
    String xSql; // cau lenh query

    public Form1() {
        initComponents();
        dt = (DefaultTableModel) tbl1.getModel();
        connectToDB();
        display();
    }

    void connectToDB() {
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            con = t.getConnection();
            System.out.println("Connection is successful.");
        } catch (Exception e) {
            System.out.println("Connection failed.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSalary = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtBonus = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnSort = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnResult = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResult = new javax.swing.JTextArea();
        btnDisplay = new javax.swing.JButton();
        btnDeleteAllData = new javax.swing.JButton();
        btnAdd2 = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Employees management");

        jLabel2.setText("Enter new employee:");

        jLabel3.setText("Code:");

        jLabel4.setText("Name:");

        jLabel5.setText("Salary:");

        jLabel6.setText("Bonus:");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnSort.setText("Sort");
        btnSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortActionPerformed(evt);
            }
        });

        tbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Name", "Salary", "Bonus"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl1);

        jLabel7.setText("Enter code to be searched: ");

        btnResult.setText("Search Result: ");
        btnResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultActionPerformed(evt);
            }
        });

        txtResult.setColumns(20);
        txtResult.setRows(5);
        jScrollPane2.setViewportView(txtResult);

        btnDisplay.setText("Display");
        btnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayActionPerformed(evt);
            }
        });

        btnDeleteAllData.setText("Delete all data");
        btnDeleteAllData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAllDataActionPerformed(evt);
            }
        });

        btnAdd2.setText("Add2");
        btnAdd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd2ActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(btnResult, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(btnAdd)
                                        .addGap(29, 29, 29)
                                        .addComponent(btnSort)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnDisplay)
                                        .addGap(26, 26, 26)
                                        .addComponent(btnDeleteAllData)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnAdd2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41)
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41)
                                        .addComponent(jLabel6)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnDelete)
                                        .addGap(16, 16, 16))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtBonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnSort)
                    .addComponent(btnDisplay)
                    .addComponent(btnDeleteAllData)
                    .addComponent(btnAdd2)
                    .addComponent(btnDelete))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnResult)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // kiem tra xem id da co trong table chua
    public boolean isExist(String xCode) {
        int n, i;
        String s;
        n = tbl1.getRowCount();
        for (i = 0; i < n; i++) {
            s = (String) tbl1.getValueAt(i, 0);

            if (s != null && s.trim().equalsIgnoreCase(xCode.trim())) {
                return (true);
            }
        }
        return (false);
    }

    // kiem tra id da co trong database chua
    public boolean isExistInDatabase(String xCode) {
        try {
            xSql = "Select Code from EMPLOYEE";
            statement = con.createStatement();
            rs = statement.executeQuery(xSql);
            while (rs.next()) { // duyet 1 row
                String id = rs.getString("Code"); // ID if column name "code"
                if (id.trim().equalsIgnoreCase(xCode.trim())) {
                    return true;
                }
            }
            rs.close();
        } catch (Exception e) {

        }
        return false;
    }


    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String code = txtCode.getText().trim();
        String name = txtName.getText().trim();
        String xSalary = txtSalary.getText().trim();
        String xBonus = txtBonus.getText().trim();

        boolean isOk = true;
        if (code.equals("")) {
            isOk = false;
        }
        if (name.equals("")) {
            isOk = false;
        }
        if (xSalary.equals("")) {
            isOk = false;
        }
        if (xBonus.equals("")) {
            isOk = false;
        }
        if (!isOk) {
            JOptionPane.showMessageDialog(null, "The data cannot be empty!");
            return;
        }

        int salary = Integer.parseInt(xSalary);
        int bonus = Integer.parseInt(xBonus);
        if (isExistInDatabase(code)) {
            JOptionPane.showMessageDialog(null, "This code already exist in database! Cannot add");
            return;
        }
//        if (isExist(code)) {
//            JOptionPane.showMessageDialog(null, "This code already exist! Cannot add");
//            return;
//        }
        try {
            xSql = "INSERT INTO EMPLOYEE (Code,Name,Salary,Bonus) VALUES(?,?,?,?)";
            //xSql = "INSERT INTO EMPLOYEE (Code,Name,Salary,Bonus) VALUES(B10,Nguyen Van A,2000,100)";
            PreparedStatement pst = con.prepareStatement(xSql);
            pst.setString(1, code);
            pst.setString(2, name);
            pst.setInt(3, salary);
            pst.setInt(4, bonus);
//            Object[] a = {code, name, salary, bonus};
//            dt.addRow(a);
            pst.executeUpdate();
            display();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultActionPerformed
        String search = txtSearch.getText().trim();
        int check = 0;
        try {
            xSql = "SELECT * FROM EMPLOYEE WHERE Code = " + "'" + search + "'";
            statement = con.createStatement();
            rs = statement.executeQuery(xSql);
            while (rs.next()) {
                String Code = rs.getString("Code");
                String Name = rs.getString("Name");
                int Salary = rs.getInt("Salary");
                int Bonus = rs.getInt("Bonus");
                txtResult.setText("Emp found: \nCode: " + Code + "\nName: " + Name + "\nSalary: " + Salary + "\nBonus: " + Bonus);
                check = 1;
                break;

            }
            if (check == 0) {
                txtResult.setText("Emp not Found!");
            }
            rs.close();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_btnResultActionPerformed

    void clearTable() {
        int n = dt.getRowCount();
        for (int i = 0; i < n; i++) {
            dt.removeRow(0);
        }
    }

    void display() {
        try {
            xSql = "Select * from Employee";
            statement = con.createStatement();
            rs = statement.executeQuery(xSql);
            clearTable();
            while (rs.next()) {
                String Code = rs.getString("Code");
                String Name = rs.getString("Name");
                int Salary = rs.getInt("Salary");
                int Bonus = rs.getInt("Bonus");

                Object[] a = {Code, Name, Salary, Bonus};
                dt.addRow(a);
            }
            rs.close();
        } catch (Exception e) {
        }
    }
    private void btnDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayActionPerformed
        display();
    }//GEN-LAST:event_btnDisplayActionPerformed

    private void btnSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortActionPerformed
        try {
            xSql = "SELECT * FROM EMPLOYEE ORDER BY Salary ";
            statement = con.createStatement();
            rs = statement.executeQuery(xSql);
            clearTable();
            while (rs.next()) {
                String Code = rs.getString("Code");
                String Name = rs.getString("Name");
                int Salary = rs.getInt("Salary");
                int Bonus = rs.getInt("Bonus");

                Object[] a = {Code, Name, Salary, Bonus};
                dt.addRow(a);
            }
            rs.close();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSortActionPerformed

    private void btnDeleteAllDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAllDataActionPerformed
//        try {
//            xSql = "DELETE FROM EMPLOYEE";
//            statement = con.createStatement();
//
//            rs = statement.executeQuery(xSql);
//
//        } catch (Exception e) {
//        }
//        clearTable();
    }//GEN-LAST:event_btnDeleteAllDataActionPerformed

    private void btnAdd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd2ActionPerformed
        String code = "9";
        String name = "A";
        int salary = 2;
        int bonus = 1;
        try {
            xSql = "INSERT INTO EMPLOYEE (Code,Name,Salary,Bonus) VALUES(?,?,?,?)";
            //xSql = "INSERT INTO EMPLOYEE (Code,Name,Salary,Bonus) VALUES(B10,Nguyen Van A,2000,100)";
            PreparedStatement pst = con.prepareStatement(xSql);
            pst.setString(1, code);
            pst.setString(2, name);
            pst.setInt(3, salary);
            pst.setInt(4, bonus);
            Object[] a = {code, name, salary, bonus};
//            dt.addRow(a);
            pst.executeUpdate();
            //display();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_btnAdd2ActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            xSql = "DELETE FROM EMPLOYEE where code = '9'";
            statement = con.createStatement();

            rs = statement.executeQuery(xSql);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAdd2;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteAllData;
    private javax.swing.JButton btnDisplay;
    private javax.swing.JButton btnResult;
    private javax.swing.JButton btnSort;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl1;
    private javax.swing.JTextField txtBonus;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextArea txtResult;
    private javax.swing.JTextField txtSalary;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
